### ISSUE TITLE
url encoded slash in ALLURE_PROJECT_PATH

### ISSUE THREAD

**Issue by abenaguev** [andrcuns/allure-report-publisher#152]
Hi. Tryed to use `ALLURE_PROJECT_PATH: ${CI_PROJECT_PATH}` for trgiggered pipeline. Got this in output: `Server responded with code 404, message: 404 Project Not Found. Request URI: https://gitlab-url/api/v4/projects/namespace%2Fproject/merge_requests/205`. I'm absolutly shure that is not any tools in pipeline nor gitlab doing that. And can't see that in publisher's code. May ruby gitlab client do this? (it works perfectly in regular pipelines)

upd. Tryed with `ALLURE_PROJECT_PATH: 'group/project'` whith the same results

**Comment by andrcuns** [comment]
The `gitlab` api client url encodes the path, that is how gitlab api is supposed to work, so it's expected.

`404` usually happens when authentication to gitlab is not setup correctly, wrong or missing auth token, incorrect token permissions etc.

**Comment by abenaguev** [comment]
I'm absolutly shure that checked all of this( ok, thanks, we'll see
