### ISSUE TITLE
"allure-report-publisher: command not found" although the installation completed successfully before

### ISSUE THREAD

**Issue by nhantrantr** [andrcuns/allure-report-publisher#312]
Hi @andrcuns ,

Thank you very much for your great effort. Unfortunately, I got the `allure-report-publisher: command not found` when trying to run command-line `allure-report-publisher upload s3` to publish my generated allure-results from my local to S3 bucket. Could you please help me to take a look and fix it? In case there is something wrong or missing from my configuration, Could you please share with me some hints to make it work. I am a completely newbie to the Ruby application.

**Environment:**
allure-report-publisher-0.8.0
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin21]

**Steps to reproduce:**
- Install `allure-report-publisher` by gem with commandline `gem install allure-report-publisher`
- Then using command to to generate and upload allure-results to S3 bucket `allure-report-publisher upload s3 --result-files-glob='<path to my local allure-results/*>' --bucket='<my bucket name>' --prefix='<myself prefix>'`

**Actual Result:**
`-sh: allure-report-publisher: command not found` is returned

Please find more details in my following captured
<img width="585" alt="Screen Shot 2022-05-30 at 21 06 32" src="https://user-images.githubusercontent.com/88174361/171010842-e6bc2914-c1d8-404b-a553-212e81d1be8f.png">

**Comment by andrcuns** [comment]
Hei @nhantrantr!

Problem is most like due to installing the gem with `sudo`. You should not install gems as root.

Take note, this tool underneath also requires for `allure` cli to be present which is the one that generates the report itself. You can install it via `brew install allure` if on macos for example.

Tool in this repo is also packaged as docker container so no additional dependencies need to be installed but that requires additionally mounting volumes and passing in the environment variables mentioned in the readme.

**Comment by nhantrantr** [comment]
Hi @andrcuns ,

Thank you very much for your quick reply. I tried to uninstall the allure-report-publisher by command `sudo gem uninstall allure-report-publisher`, then install it again without `sudo`

I also tried to install allure cli, then tried to upload my allure results again. But the error `sh: allure-report-publisher: command not found` still occurs on my side.

I already had the configuration for .aws credentials already and passed the required variable as you can see in my upload command. They are blurred due to the security policy of my project

<img width="1417" alt="image" src="https://user-images.githubusercontent.com/88174361/171085581-35e347f8-2498-4464-97db-4f463a9cffc7.png">

**Comment by andrcuns** [comment]
It is something with ruby installation. Shell doesn't see installed gem executables for some reason, probably because the executables dir is not in the PATH. I'm not sure how to debug this as there are many different ways ruby installation can be setup.
