### ISSUE TITLE
Empty reports after generating and pushing to S3

### ISSUE THREAD

**Issue by asprada** [andrcuns/allure-report-publisher#408]
Hey,
I'm using your tool to upload allure reports to AWS. I used the image provided on GitHub with the `latest` tag (at that time it should be version 0.10.0). And at that moment everything was fine. Unfortunately, uploading started to behave not as expected with the current latest tag (1.2.0 and also not working with any other tag I used to pull the image).

The version when everything worked correctly was 0.10.0. I tried to download an image with that tag, but it's not working at all.
```
docker pull andrcuns/allure-report-publisher:0.10.0
0.10.0: Pulling from andrcuns/allure-report-publisher
9621f1afde84: Already exists
d2cd49031887: Already exists
6ba07b9d8a4e: Already exists
727a7e518ee9: Already exists
caf782dda985: Already exists
bd6232709a14: Pulling fs layer
549fd55ea05a: Pulling fs layer
68b0c1f8e3a9: Pulling fs layer
92eca898f16d: Pulling fs layer
92eca898f16d: Waiting
68b0c1f8e3a9: Verifying Checksum
68b0c1f8e3a9: Download complete
549fd55ea05a: Verifying Checksum
549fd55ea05a: Download complete
92eca898f16d: Verifying Checksum
92eca898f16d: Download complete
bd6232709a14: Download complete
bd6232709a14: Pull complete
549fd55ea05a: Pull complete
68b0c1f8e3a9: Pull complete
92eca898f16d: Pull complete
Digest: sha256:e6ecab216a112e3731097eecd1de26f66561091c0977cc550740df477ea37f91
Status: Downloaded newer image for andrcuns/allure-report-publisher:0.10.0
docker.io/andrcuns/allure-report-publisher:0.10.0

ERROR: "allure-report-publisher upload" was called with arguments "s3 --results-glob=allure-results/* --bucket=allure-reports --prefix=allure-reports --debug --color"
```

What's the issue with the latest version? After running tests I lost my previous tests and can only access the empty template of allure reports. Nothing tests-related is transferred to the S3 bucket.

<img width="1637" alt="Screen Shot 2022-11-04 at 11 03 56 AM" src="https://user-images.githubusercontent.com/6390698/200068496-d3df74f7-2aa0-4fef-8316-6ce300982fd9.png">

Command I use
```
allure-report-publisher upload s3 \
    --results-glob="allure-results/*" \
    --bucket="allure-reports" \
    --prefix="allure-reports" \
    --debug \
    --color
```

Could you guide me on what could be wrong?

Log stash (with --debug option). I removed some `is not a directory` lines to save description space. After 1 tests run I have about 1,4k files in that directory.
> allure-report-publisher upload s3 --results-glob=allure-results/* --bucket=allure-reports --prefix=allure-reports --debug --color
> Generating allure report
> [✔] generating ... done
> == DEBUG LOG OUTPUT ==
> [2022-11-03 23:42:21 +0000] Executing command 'which allure'
> [2022-11-03 23:42:21 +0000] Glob 'allure-results/*' found 429 paths
> [2022-11-03 23:42:21 +0000] Created tmp folder for common data: '/tmp/allure-results20221103-17-oe0tx2'
> [2022-11-03 23:42:21 +0000] Created tmp folder for history data: '/tmp/allure-results20221103-17-oe0tx2/history'
> [2022-11-03 23:42:21 +0000] Downloading previous run history
> [2022-11-03 23:42:21 +0000] Downloaded 'categories-trend.json' as '/tmp/allure-results20221103-17-oe0tx2/history/categories-trend.json'
> [2022-11-03 23:42:21 +0000] Downloaded 'duration-trend.json' as '/tmp/allure-results20221103-17-oe0tx2/history/duration-trend.json'
> [2022-11-03 23:42:21 +0000] Downloaded 'history-trend.json' as '/tmp/allure-results20221103-17-oe0tx2/history/history-trend.json'
> [2022-11-03 23:42:22 +0000] Downloaded 'history.json' as '/tmp/allure-results20221103-17-oe0tx2/history/history.json'
> [2022-11-03 23:42:22 +0000] Downloaded 'retry-trend.json' as '/tmp/allure-results20221103-17-oe0tx2/history/retry-trend.json'
> [2022-11-03 23:42:22 +0000] Generating allure report
> [2022-11-03 23:42:22 +0000] Executing command 'allure generate --clean --output /tmp/allure-report-1667518942 /tmp/allure-results20221103-17-oe0tx2 allure-results/008a6b78-394b-43b6-8150-a2d4709c3660-result.json allure-results/00a313d5-57b0-4922-803b-4f134ec3bc7b-result.json [...] allure-results/fdc34d25-1239-4f7c-95da-af47107bfa7a-result.json allure-results/fe7c0ebf-0743-41ba-ae36-cc708a6c3ba7-result.json allure-results/fec5c9f0-6320-41b5-96b0-5ca37c576f3d-result.json allure-results/ff9782b7-c59e-43e4-bdb3-f38abd88cd29-attachment.ZIP'
> [2022-11-03 23:42:23 +0000] Generated allure report. Out: allure-results/008a6b78-394b-43b6-8150-a2d4709c3660-result.json is not a directory
> allure-results/00a313d5-57b0-4922-803b-4f134ec3bc7b-result.json is not a directory
> allure-results/00ae21bf-c7f2-4354-a82b-451850f4f2cf-result.json is not a directory
> allure-results/00e9f04f-d975-4f33-bb41-2608d8e3dd05-result.json is not a directory
[...]
> allure-results/fd72fd59-5a4c-4f49-92a0-1e499a6dd046-result.json is not a directory
> allure-results/fdaf806e-d2ac-4b02-a7c0-d0677d0217f4-result.json is not a directory
> allure-results/fdc34d25-1239-4f7c-95da-af47107bfa7a-result.json is not a directory
> allure-results/fe7c0ebf-0743-41ba-ae36-cc708a6c3ba7-result.json is not a directory
> allure-results/fec5c9f0-6320-41b5-96b0-5ca37c576f3d-result.json is not a directory
> allure-results/ff9782b7-c59e-43e4-bdb3-f38abd88cd29-attachment.ZIP is not a directory
> Report successfully generated to /tmp/allure-report-1667518942
> == DEBUG LOG OUTPUT ==
> Uploading allure report to s3
> [✔] uploading ... done
> == DEBUG LOG OUTPUT ==
> [2022-11-03 23:42:23 +0000] Uploading report files
> [2022-11-03 23:42:23 +0000] Uploading '38' files in '8' threads
> [2022-11-03 23:42:24 +0000] Finished upload successfully
> == DEBUG LOG OUTPUT ==

**Comment by andrcuns** [comment]
Yes, it is expected. [1.0](https://github.com/andrcuns/allure-report-publisher/pull/367) had a breaking change to remove local copy operations, so `--results-glob` now has to return folders with allure result files rather than files themselves.

So in this case it will be `--results-glob=allure-results`

**Comment by asprada** [comment]
Thank you for your support. I've changed that but still no success.
```
allure-report-publisher upload s3 '--results-glob=allure-results' '--bucket=allure-reports' '--prefix=allure-reports' --color
Generating allure report
[✖] generating ... failed
Is a directory - read
```

**Comment by asprada** [comment]
Thank you, everything is working fine now.
