### ISSUE TITLE
Uploading fails if attachments include any "har" files 

### ISSUE THREAD

**Issue by kormachevt** [andrcuns/allure-report-publisher#489]
Hi! 

**Context:**
- action: `andrcuns/allure-publish-action@v2.3.0`
- storageType: s3

**Problem:**

If `allure-result` folder includes an HTTP archive file - any `*.har` the uploading fails with an error
![Screenshot 2023-05-26 at 16 07 24](https://github.com/andrcuns/allure-report-publisher/assets/58318654/0abbb1a3-165d-4ccd-9d1b-56baa1b13302)

I verified this guess by manually removing those files from `allure-results` folder and then generated report started to upload successfully.

I think it throws [here](https://github.com/andrcuns/allure-report-publisher/blob/f9aebfc3cd8ac29ba07d1cad565b664c60289bf5/lib/allure_report_publisher/lib/uploaders/s3.rb#L102)

My bet is that the library can't handle such a format.
Maybe it would be convenient to set some default content type for cases like this, for example `"application/octet-stream"`

**Comment by andrcuns** [comment]
Thanks for the issue. Yes, probably `MiniMime` library is unable to understand the content type for particular file.

It looks like one alternative would also be migrating to https://github.com/rails/marcel as it seems to have a larger db of supported files and is what ruby on rails uses. I will look in to it.

Having a default content-type might be one way, but I'm not sure if it would not introduce unpredictable behaviours. Maybe it's better to raise understandable error and keep additional custom mapping as well which could be extended if someone runs in to similar issue with some exotic file type.

**Comment by andrcuns** [comment]
I opted for using `application/octet-stream` as default. Given it only affects uploads to s3 and `marcel` could potentially introduce some performance degradation, it felt a bit overkill.

If this problem is common enough, we can think about introducing a mapping of manually maintained unsupported types

**Comment by kormachevt** [comment]
Awesome! Thank you for the fix.
