### ISSUE TITLE
Issue with updating PR report after changing description

### ISSUE THREAD

**Issue by bslabiak** [andrcuns/allure-report-publisher#592]
updatePR : `description`

Steps to reproduce:
1. Run test
2. Report has been posted into PR description
3. edit description
4. Run test again

Results:
Test report is not being updated on description and still display old report (without editing step it seems not to appear)

--------------

updatePR : `comment`

Behaviour is very similar but it is rare to edit a comment.
Next run of tests in same PR is updating same comment.

Is this possible to post new comment after each run to track history of test results properly?

**Comment by andrcuns** [comment]
I believe this should be fixed by https://github.com/andrcuns/allure-report-publisher/pull/738
